In [5]:
import pandas as pd
from path import Path
file_path = Path("final_clean_data.csv")
loans_df = pd.read_csv(file_path)
loans_df.head()

,title,year released,certificate,duration_min,genre,rating,votes,age
0,Scarface,1932,PG,93,Action,7.7,"28,107",90
1,Dumbo,1941,G,64,Animation,7.2,"131,896",81
2,Nazi Concentration Camps,1945,Not Rated,59,Documentary,8.3,"1,481",77
3,Know Your Enemy - Japan,1945,Not Rated,63,Documentary,6.0,800,77
4,Along Came Jones,1945,Approved,90,Comedy,6.4,"2,163",77

In [6]:
pip install path.py

Requirement already satisfied: path.py in c:\users\natnael\anaconda3\envs\mlenv\lib\site-packages (12.5.0)
Requirement already satisfied: path in c:\users\natnael\anaconda3\envs\mlenv\lib\site-packages (from path.py) (16.5.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
loans_binary_encoded = pd.get_dummies(loans_df, columns=["rating"])
loans_binary_encoded.head()

,title,year released,certificate,duration_min,genre,votes,age,rating_1.7,rating_2.0,rating_2.1,...,rating_8.8,rating_8.9,rating_9.0,rating_9.1,rating_9.2,rating_9.3,rating_9.4,rating_9.5,rating_9.6,rating_9.9
0,Scarface,1932,PG,93,Action,"28,107",90,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Dumbo,1941,G,64,Animation,"131,896",81,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Nazi Concentration Camps,1945,Not Rated,59,Documentary,"1,481",77,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Know Your Enemy - Japan,1945,Not Rated,63,Documentary,800,77,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Along Came Jones,1945,Approved,90,Comedy,"2,163",77,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df2 = loans_df.copy()
df2['rating'] = le.fit_transform(df2['rating'])

In [11]:
label_encoder=LabelEncoder()
loans_df["rating_le"]=label_encoder.fit_transform(loans_df["rating"])
loans_df.head()

,title,year released,certificate,duration_min,genre,rating,votes,age,rating_le
0,Scarface,1932,PG,93,Action,7.7,"28,107",90,57
1,Dumbo,1941,G,64,Animation,7.2,"131,896",81,52
2,Nazi Concentration Camps,1945,Not Rated,59,Documentary,8.3,"1,481",77,63
3,Know Your Enemy - Japan,1945,Not Rated,63,Documentary,6.0,800,77,40
4,Along Came Jones,1945,Approved,90,Comedy,6.4,"2,163",77,44

In [13]:
loans_df = loans_df.drop(["rating", "rating_le"], axis=1)
loans_df.head()

,title,year released,certificate,duration_min,genre,votes,age
0,Scarface,1932,PG,93,Action,"28,107",90
1,Dumbo,1941,G,64,Animation,"131,896",81
2,Nazi Concentration Camps,1945,Not Rated,59,Documentary,"1,481",77
3,Know Your Enemy - Japan,1945,Not Rated,63,Documentary,800,77
4,Along Came Jones,1945,Approved,90,Comedy,"2,163",77